version: "3"

networks:
  monitoring-internal:

volumes:
  gcnet-input:
  gcnet-output:

services:
  api:
    container_name: monitoring_api
    image: "${INTERNAL_REG}/monitoring-api:${APP_VERSION}-debug"
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - APP_MAINTAINER=${APP_MAINTAINER}
        - DEVOPS_MAINTAINER=${DEVOPS_MAINTAINER}
        - EXTERNAL_REG=${EXTERNAL_REG}
      target: debug
    volumes:
      - ./monitoring-api:/opt/app
      - gcnet-input:/opt/app/gcnet/input
      - gcnet-output:/opt/app/gcnet/output
    ports:
      - "9111:8080"
    extra_hosts:
      - "pgdboapp.wsl.ch:10.30.1.156"
    env_file:
      - monitoring-api/project/.env
    environment:
      DEBUG: "True"
    networks:
      - monitoring-internal
    restart: unless-stopped
